### ISSUE TITLE
Add support for calling functions via module

### ISSUE THREAD

**Issue by cinova** [lfex/logjam#3]
The logjam `error` function is problematic, due to the Erlang `error` function. Also, other macros in different software packages may have defined that name. It would be nice to have the option of not including the logjam functions via `(inlcude-lib ...)`, but rather as `mod:fun` calls, if necessary.

**Comment by yurrriq** [comment]
I'm pretty sure this can be closed.

**Comment by oubiwann** [comment]
Yup.
